---
resources:
  - name: testing-resource
    type: git
    source:
      uri: https://github.com/kuttidog/concourse_demo.git
      branch: master

jobs:
  - name: job-pass-files
    plan:
      - get: testing-resource
      - task: create-some-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}

          inputs:
            - name: testing-resource
          outputs:
            - name: create-files

          run:
            path: testing-resource/scripts/input_file.sh

      - task: show-some-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}

          inputs:
            - name: testing-resource
            - name: create-files

          run:
            path: testing-resource/scripts/output_file.sh

